name: srgot
channels:
  - defaults
dependencies:
  - python=3.7
  - tensorflow 
  - lightgbm 
  - scikit-learn
  - cudatoolkit 
  - pytorch
  - torchvision
  - pip
  - pip:
    - wandb==0.12.15
    - aif360
    - torchinfo
    - frozendict
    - qhoptim
    - fairlearn 
    - folktables
    - -e .

