model_tag:
  value: "mlp-test"

model_type:
  value: "mlp"
criterion_name:
  value: "ce"

epochs:
  value: 10
batch_size:
  value: 128
num_layers:
  value: 3
d_hidden:
  value: 256
dropout_prob:
  value: null
optimizer:
  value: "sgd"
momentum:
  value: 0.1
weight_decay:
  value: 0.0001
learning_rate:
  value: 0.001
