DORO_MODEL = "doro"  # DORO model
EXPGRAD_MODEL = "expgrad"  # exponentiated gradient method; Agarwal et al.
FAST_DRO_MODEL = "fastdro"  # fast DRO, via levy et al 2020
GBM_MODEL = "gbm"
GROUP_DRO_MODEL = "groupdro"  # Group DRO
HISTGBM_MODEL = "histgbm"  # lightgbm-inspired histogram boosting classifier
IWC_MODEL = "iwc"
LFR_PREPROCESSOR_MODEL = "preprocessor"  # LFR; Zemel et al.
LIGHTGBM_MODEL = "lightgbm"
POSTPROCESSOR_MODEL = "postprocessor"  # Eq. Odds Postprocessing; Hardt et al.
LR_MODEL = "lr"  # vanilla logistic regression
L2_MODEL = "l2lr"
MLP_MODEL = "mlp"
RANDOM_FOREST_MODEL = "randomforest"
SGD = "sgd"
SVM_MODEL = "svm"
XGBOOST_MODEL = "xgboost"
MARGINAL_DRO_MODEL = "marginal_dro"
MWLD_MODEL = "mwld"  # loss variance regularizer; eq (10)
DP_CONSTRAINT = "demographicparity"
EO_CONSTRAINT = "equalizedodds"
ERROR_RATE_PARITY_CONSTRAINT = "error_rate_parity"
